//! Cold layout snapshots for the Phantom web engine.
//!
//! This crate transforms DOM plus immutable computed style into a flat,
//! geometry-oriented snapshot. The snapshot has no pointers or references into
//! the DOM.
//!
//! The current milestone adds the first Inline Formatting Context:
//!
//! - explicit line boxes;
//! - inline text fragments;
//! - wrapping at collapsible whitespace;
//! - `<br>` forced line breaks;
//! - `<pre>` hard-line preservation;
//! - text-decoration propagation into text fragments.
//!
//! Paint consumes only this cold snapshot and computed style.

#![forbid(unsafe_code)]

use std::mem;

use phantom_css::{
    BoxSizing, ComputedStyle, Display as CssDisplay, EdgeSizes, FontFamily as CssFontFamily,
    FontStyle as CssFontStyle, FontWeight as CssFontWeight, Length, StyleMap,
};
use phantom_dom::{Document, NodeId, NodeKind};
use phantom_text::{
    FallbackTextShaper, FontFamily as TextFontFamily, FontSlant as TextFontSlant,
    FontWeight as TextFontWeight, TextShaper, TextStyle,
};
use thiserror::Error;

/// Stable index of a box inside one [`LayoutSnapshot`].
///
/// The identifier is intentionally a compact integer instead of a pointer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct LayoutId(u32);

impl LayoutId {
    /// Returns the compact numeric index.
    #[must_use]
    pub const fn as_u32(self) -> u32 {
        self.0
    }
}

/// Physical rectangle generated by layout, in logical pixels.
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct Rect {
    x: f32,
    y: f32,
    width: f32,
    height: f32,
}

impl Rect {
    /// Creates a physical rectangle.
    #[must_use]
    pub const fn new(x: f32, y: f32, width: f32, height: f32) -> Self {
        Self {
            x,
            y,
            width,
            height,
        }
    }

    /// Returns the horizontal origin.
    #[must_use]
    pub const fn x(self) -> f32 {
        self.x
    }

    /// Returns the vertical origin.
    #[must_use]
    pub const fn y(self) -> f32 {
        self.y
    }

    /// Returns the rectangle width.
    #[must_use]
    pub const fn width(self) -> f32 {
        self.width
    }

    /// Returns the rectangle height.
    #[must_use]
    pub const fn height(self) -> f32 {
        self.height
    }

    /// Returns the bottom coordinate.
    #[must_use]
    pub fn bottom(self) -> f32 {
        self.y + self.height
    }
}

/// Structural role of one cold layout box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LayoutKind {
    /// Synthetic document root.
    Root,

    /// Block formatting box.
    Block,

    /// Flex formatting container.
    ///
    /// Flex containers still use vertical block flow in this milestone.
    Flex,

    /// One explicit line generated by the Inline Formatting Context.
    Line,

    /// One positioned UTF-8 text fragment inside a line box.
    Text {
        /// UTF-8 byte offset in the shared text buffer.
        start: u32,

        /// UTF-8 byte length in the shared text buffer.
        len: u32,

        /// Effective underline decoration propagated by inline layout.
        underline: bool,
    },
}

/// One compact box in a cold [`LayoutSnapshot`].
///
/// Relationships use [`LayoutId`] indices. No `Rc`, `RefCell`, boxed child
/// trees, raw pointers, or references into the DOM are stored here.
#[derive(Debug, Clone, PartialEq)]
pub struct LayoutBox {
    id: LayoutId,
    source_node: NodeId,
    parent: Option<LayoutId>,
    first_child: Option<LayoutId>,
    next_sibling: Option<LayoutId>,
    kind: LayoutKind,
    rect: Rect,
    margin: EdgeSizes,
    padding: EdgeSizes,
    border: EdgeSizes,
}

impl LayoutBox {
    /// Returns this box's stable snapshot-local identifier.
    #[must_use]
    pub const fn id(&self) -> LayoutId {
        self.id
    }

    /// Returns the originating DOM identifier by value.
    ///
    /// This is a numeric handle for future hit-testing and event routing. It
    /// is not a DOM pointer.
    #[must_use]
    pub const fn source_node(&self) -> NodeId {
        self.source_node
    }

    /// Returns the parent box.
    #[must_use]
    pub const fn parent(&self) -> Option<LayoutId> {
        self.parent
    }

    /// Returns the first child box.
    #[must_use]
    pub const fn first_child(&self) -> Option<LayoutId> {
        self.first_child
    }

    /// Returns the next sibling box.
    #[must_use]
    pub const fn next_sibling(&self) -> Option<LayoutId> {
        self.next_sibling
    }

    /// Returns the box role.
    #[must_use]
    pub const fn kind(&self) -> LayoutKind {
        self.kind
    }

    /// Returns the generated border-box rectangle.
    #[must_use]
    pub const fn rect(&self) -> Rect {
        self.rect
    }

    /// Returns the computed margins copied into the cold snapshot.
    #[must_use]
    pub const fn margin(&self) -> EdgeSizes {
        self.margin
    }

    /// Returns the computed padding copied into the cold snapshot.
    #[must_use]
    pub const fn padding(&self) -> EdgeSizes {
        self.padding
    }

    /// Returns effective border widths copied into the cold snapshot.
    #[must_use]
    pub const fn border(&self) -> EdgeSizes {
        self.border
    }
}

/// Immutable, flat layout result prepared for paint and composition.
#[derive(Debug, Clone, Default)]
pub struct LayoutSnapshot {
    boxes: Vec<LayoutBox>,
    text: String,
    viewport_width: f32,
    content_height: f32,
}

impl LayoutSnapshot {
    /// Creates an empty layout snapshot.
    #[must_use]
    pub fn empty(viewport_width: f32) -> Self {
        Self {
            boxes: Vec::new(),
            text: String::new(),
            viewport_width: sanitize_viewport_width(viewport_width),
            content_height: 0.0,
        }
    }

    /// Returns all layout boxes in contiguous storage.
    #[must_use]
    pub fn boxes(&self) -> &[LayoutBox] {
        &self.boxes
    }

    /// Returns one layout box by compact identifier.
    #[must_use]
    pub fn get(&self, id: LayoutId) -> Option<&LayoutBox> {
        let index = usize::try_from(id.0).ok()?;
        self.boxes.get(index)
    }

    /// Returns the text associated with one text-fragment box.
    #[must_use]
    pub fn text_for(&self, layout_box: &LayoutBox) -> Option<&str> {
        let LayoutKind::Text { start, len, .. } = layout_box.kind else {
            return None;
        };

        let start = usize::try_from(start).ok()?;
        let len = usize::try_from(len).ok()?;
        let end = start.checked_add(len)?;

        self.text.get(start..end)
    }

    /// Returns the number of cold layout boxes.
    #[must_use]
    pub fn len(&self) -> usize {
        self.boxes.len()
    }

    /// Returns `true` when no layout boxes exist.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.boxes.is_empty()
    }

    /// Returns the number of explicit line boxes.
    #[must_use]
    pub fn line_count(&self) -> usize {
        self.boxes
            .iter()
            .filter(|layout_box| layout_box.kind == LayoutKind::Line)
            .count()
    }

    /// Returns the number of text fragments generated by inline layout.
    #[must_use]
    pub fn text_fragment_count(&self) -> usize {
        self.boxes
            .iter()
            .filter(|layout_box| matches!(layout_box.kind, LayoutKind::Text { .. }))
            .count()
    }

    /// Returns the shared UTF-8 text-buffer size in bytes.
    #[must_use]
    pub fn text_bytes(&self) -> usize {
        self.text.len()
    }

    /// Estimates cold-snapshot storage reserved by its two contiguous buffers.
    ///
    /// The value intentionally excludes allocator bookkeeping and the small
    /// [`LayoutSnapshot`] header itself.
    #[must_use]
    pub fn estimated_storage_bytes(&self) -> usize {
        self.boxes
            .capacity()
            .saturating_mul(mem::size_of::<LayoutBox>())
            .saturating_add(self.text.capacity())
    }

    /// Returns the viewport width used for this layout pass.
    #[must_use]
    pub const fn viewport_width(&self) -> f32 {
        self.viewport_width
    }

    /// Returns the measured vertical extent of the document.
    #[must_use]
    pub const fn content_height(&self) -> f32 {
        self.content_height
    }
}

/// Errors produced while constructing a compact layout snapshot.
#[derive(Debug, Error, Clone, Copy, PartialEq, Eq)]
pub enum LayoutError {
    /// More boxes were requested than a compact [`LayoutId`] can represent.
    #[error("layout box capacity exceeded")]
    BoxCapacityExceeded,

    /// The shared text buffer can no longer be addressed by compact ranges.
    #[error("layout text-buffer capacity exceeded")]
    TextCapacityExceeded,
}

/// Builds a cold, flat layout snapshot.
///
/// The current geometry algorithm supports block flow plus a first Inline
/// Formatting Context. Inline text wraps only at collapsible whitespace.
/// Unbreakable words may overflow horizontally, matching the conservative
/// behavior expected before `overflow-wrap` is implemented.
///
/// # Errors
///
/// Returns [`LayoutError`] if compact box or text index space is exceeded.
pub fn build_layout_snapshot(
    document: &Document,
    styles: &StyleMap,
    viewport_width: f32,
) -> Result<LayoutSnapshot, LayoutError> {
    let shaper = FallbackTextShaper;

    build_layout_snapshot_with_shaper(document, styles, viewport_width, &shaper)
}

/// Builds a cold layout snapshot using an explicit text backend.
///
/// This is the stable boundary that lets Phantom replace the fallback metrics
/// engine with a future real font/shaping backend without teaching layout
/// about font files, platform APIs, glyph caches, or the renderer.
///
/// # Errors
///
/// Returns [`LayoutError`] if compact box or text index space is exceeded.
pub fn build_layout_snapshot_with_shaper<S: TextShaper + ?Sized>(
    document: &Document,
    styles: &StyleMap,
    viewport_width: f32,
    shaper: &S,
) -> Result<LayoutSnapshot, LayoutError> {
    let viewport_width = sanitize_viewport_width(viewport_width);

    let mut builder = LayoutBuilder::new(document, styles, shaper);

    let root = builder.push_box(BoxSpec {
        source_node: document.root(),
        parent: None,
        kind: LayoutKind::Root,
        rect: Rect::new(0.0, 0.0, viewport_width, 0.0),
        margin: EdgeSizes::zero(),
        padding: EdgeSizes::zero(),
        border: EdgeSizes::zero(),
    })?;

    let content_end = builder.layout_flow_children(
        document.root(),
        FlowArea {
            layout_parent: root,
            source_node: document.root(),
            x: 0.0,
            y: 0.0,
            width: viewport_width,
            underline: false,
            whitespace: WhitespaceMode::Collapse,
        },
    )?;

    builder.set_box_rect(
        root,
        Rect::new(0.0, 0.0, viewport_width, content_end.max(0.0)),
    )?;

    Ok(LayoutSnapshot {
        boxes: builder.boxes,
        text: builder.text,
        viewport_width,
        content_height: content_end.max(0.0),
    })
}

#[derive(Debug, Clone, Copy)]
enum WhitespaceMode {
    Collapse,
    Preserve,
}

#[derive(Debug, Clone, Copy)]
struct FlowArea {
    layout_parent: LayoutId,
    source_node: NodeId,
    x: f32,
    y: f32,
    width: f32,
    underline: bool,
    whitespace: WhitespaceMode,
}

#[derive(Debug, Clone, Copy)]
struct BlockContext {
    parent: LayoutId,
    x: f32,
    y: f32,
    width: f32,
}

#[derive(Debug, Clone, Copy)]
struct BoxSpec {
    source_node: NodeId,
    parent: Option<LayoutId>,
    kind: LayoutKind,
    rect: Rect,
    margin: EdgeSizes,
    padding: EdgeSizes,
    border: EdgeSizes,
}

#[derive(Debug, Clone, Copy)]
struct OpenLine {
    id: LayoutId,
    cursor_x: f32,
    used_width: f32,
    height: f32,
}

#[derive(Debug, Clone, Copy)]
struct InlineFlow {
    parent: LayoutId,
    source_node: NodeId,
    x: f32,
    cursor_y: f32,
    width: f32,
    pending_space: bool,
    line: Option<OpenLine>,
    whitespace: WhitespaceMode,
}

impl InlineFlow {
    fn new(area: FlowArea) -> Self {
        Self {
            parent: area.layout_parent,
            source_node: area.source_node,
            x: area.x,
            cursor_y: area.y,
            width: area.width.max(1.0),
            pending_space: false,
            line: None,
            whitespace: area.whitespace,
        }
    }
}

struct LayoutBuilder<'a, S: TextShaper + ?Sized> {
    document: &'a Document,
    styles: &'a StyleMap,
    shaper: &'a S,
    boxes: Vec<LayoutBox>,
    last_child: Vec<Option<LayoutId>>,
    text: String,
}

impl<'a, S: TextShaper + ?Sized> LayoutBuilder<'a, S> {
    fn new(document: &'a Document, styles: &'a StyleMap, shaper: &'a S) -> Self {
        let estimated_boxes = document.len().saturating_mul(2).min(8192);
        let estimated_text = document.len().saturating_mul(24).min(1_048_576);

        Self {
            document,
            styles,
            shaper,
            boxes: Vec::with_capacity(estimated_boxes),
            last_child: Vec::with_capacity(estimated_boxes),
            text: String::with_capacity(estimated_text),
        }
    }

    fn layout_flow_children(
        &mut self,
        dom_parent: NodeId,
        area: FlowArea,
    ) -> Result<f32, LayoutError> {
        let Some(parent_node) = self.document.node(dom_parent) else {
            return Ok(area.y);
        };

        let children = parent_node.children().to_vec();
        let mut flow = InlineFlow::new(area);

        for child_id in children {
            let Some(child) = self.document.node(child_id) else {
                continue;
            };

            match child.kind() {
                NodeKind::Comment(_) => {}

                NodeKind::Document | NodeKind::Text(_) => {
                    self.append_inline_node(child_id, &mut flow, area.underline)?;
                }

                NodeKind::Element(element) => {
                    let style = self.styles.get(child_id).cloned().unwrap_or_default();

                    if style.display() == CssDisplay::None {
                        continue;
                    }

                    if element.tag_name() == "br" {
                        let line_height = self.line_height_for(&style);

                        self.force_line_break(&mut flow, line_height)?;
                        continue;
                    }

                    match style.display() {
                        CssDisplay::Block | CssDisplay::Flex => {
                            self.finish_line(&mut flow, 0.0)?;

                            let next_y = self.layout_block_element(
                                child_id,
                                &style,
                                BlockContext {
                                    parent: area.layout_parent,
                                    x: area.x,
                                    y: flow.cursor_y,
                                    width: area.width,
                                },
                            )?;

                            flow.cursor_y = next_y;
                            flow.pending_space = false;
                        }

                        CssDisplay::Inline => {
                            self.append_inline_node(child_id, &mut flow, area.underline)?;
                        }

                        CssDisplay::None => {}
                    }
                }
            }
        }

        self.finish_line(&mut flow, 0.0)?;

        Ok(flow.cursor_y)
    }

    fn layout_block_element(
        &mut self,
        node_id: NodeId,
        style: &ComputedStyle,
        context: BlockContext,
    ) -> Result<f32, LayoutError> {
        let margin = style.margin();
        let padding = style.padding();
        let border = style.border_width();

        let horizontal_non_content =
            padding.left() + padding.right() + border.left() + border.right();

        let available_border_width = (context.width - margin.left() - margin.right()).max(0.0);

        let auto_sizing_width = match style.box_sizing() {
            BoxSizing::ContentBox => (available_border_width - horizontal_non_content).max(0.0),

            BoxSizing::BorderBox => available_border_width,
        };

        let requested_sizing_width =
            resolve_axis_length(style.width(), auto_sizing_width, context.width);

        let min_sizing_width = resolve_min_constraint(style.min_width(), context.width);

        let max_sizing_width = resolve_max_constraint(style.max_width(), context.width);

        let sizing_width = clamp_axis(requested_sizing_width, min_sizing_width, max_sizing_width);

        let (content_width, border_box_width) = match style.box_sizing() {
            BoxSizing::ContentBox => (
                sizing_width.max(0.0),
                (sizing_width + horizontal_non_content).max(0.0),
            ),

            BoxSizing::BorderBox => (
                (sizing_width - horizontal_non_content).max(0.0),
                sizing_width.max(0.0),
            ),
        };

        let x = context.x + margin.left();
        let y = context.y + margin.top();

        let kind = match style.display() {
            CssDisplay::Block => LayoutKind::Block,
            CssDisplay::Flex => LayoutKind::Flex,
            CssDisplay::Inline | CssDisplay::None => LayoutKind::Block,
        };

        let layout_id = self.push_box(BoxSpec {
            source_node: node_id,
            parent: Some(context.parent),
            kind,
            rect: Rect::new(x, y, border_box_width, 0.0),
            margin,
            padding,
            border,
        })?;

        let whitespace = if is_pre_element(self.document, node_id) {
            WhitespaceMode::Preserve
        } else {
            WhitespaceMode::Collapse
        };

        let child_content_x = x + border.left() + padding.left();

        let child_content_y = y + border.top() + padding.top();

        let children_end = self.layout_flow_children(
            node_id,
            FlowArea {
                layout_parent: layout_id,
                source_node: node_id,
                x: child_content_x,
                y: child_content_y,
                width: content_width,
                underline: style.underline(),
                whitespace,
            },
        )?;

        let measured_content_height = (children_end - child_content_y).max(0.0);

        let vertical_non_content =
            padding.top() + padding.bottom() + border.top() + border.bottom();

        let auto_sizing_height = match style.box_sizing() {
            BoxSizing::ContentBox => measured_content_height,

            BoxSizing::BorderBox => measured_content_height + vertical_non_content,
        };

        let requested_sizing_height = resolve_height_length(style.height(), auto_sizing_height);

        let min_sizing_height = resolve_min_height_constraint(style.min_height());

        let max_sizing_height = resolve_max_height_constraint(style.max_height());

        let sizing_height = clamp_axis(
            requested_sizing_height,
            min_sizing_height,
            max_sizing_height,
        );

        let border_box_height = match style.box_sizing() {
            BoxSizing::ContentBox => sizing_height + vertical_non_content,

            BoxSizing::BorderBox => sizing_height,
        }
        .max(vertical_non_content);

        self.set_box_rect(
            layout_id,
            Rect::new(x, y, border_box_width, border_box_height),
        )?;

        Ok(y + border_box_height + margin.bottom())
    }

    fn append_inline_node(
        &mut self,
        node_id: NodeId,
        flow: &mut InlineFlow,
        inherited_underline: bool,
    ) -> Result<(), LayoutError> {
        let Some(node) = self.document.node(node_id) else {
            return Ok(());
        };

        let style = self.styles.get(node_id).cloned().unwrap_or_default();
        let effective_underline = inherited_underline || style.underline();

        match node.kind() {
            NodeKind::Comment(_) => {}

            NodeKind::Document => {
                let children = node.children().to_vec();

                for child in children {
                    self.append_inline_node(child, flow, effective_underline)?;
                }
            }

            NodeKind::Text(text) => {
                self.append_text(node_id, text, &style, flow, effective_underline)?;
            }

            NodeKind::Element(element) => {
                if style.display() == CssDisplay::None {
                    return Ok(());
                }

                if element.tag_name() == "br" {
                    let line_height = self.line_height_for(&style);

                    self.force_line_break(flow, line_height)?;
                    return Ok(());
                }

                let children = node.children().to_vec();

                match style.display() {
                    CssDisplay::Inline => {
                        for child in children {
                            self.append_inline_node(child, flow, effective_underline)?;
                        }
                    }

                    CssDisplay::Block | CssDisplay::Flex => {
                        self.force_line_break(flow, style.font_size() * 1.25)?;

                        for child in children {
                            self.append_inline_node(child, flow, effective_underline)?;
                        }

                        self.force_line_break(flow, style.font_size() * 1.25)?;
                    }

                    CssDisplay::None => {}
                }
            }
        }

        Ok(())
    }

    fn append_text(
        &mut self,
        node_id: NodeId,
        text: &str,
        style: &ComputedStyle,
        flow: &mut InlineFlow,
        underline: bool,
    ) -> Result<(), LayoutError> {
        match flow.whitespace {
            WhitespaceMode::Collapse => {
                self.append_collapsed_text(node_id, text, style, flow, underline)
            }

            WhitespaceMode::Preserve => {
                self.append_preserved_text(node_id, text, style, flow, underline)
            }
        }
    }

    fn append_collapsed_text(
        &mut self,
        node_id: NodeId,
        text: &str,
        style: &ComputedStyle,
        flow: &mut InlineFlow,
        underline: bool,
    ) -> Result<(), LayoutError> {
        let mut word_start = None;

        for (index, character) in text.char_indices() {
            if character.is_whitespace() {
                if let Some(start) = word_start.take() {
                    self.append_word(node_id, &text[start..index], style, flow, underline)?;
                }

                flow.pending_space = true;
            } else if word_start.is_none() {
                word_start = Some(index);
            }
        }

        if let Some(start) = word_start {
            self.append_word(node_id, &text[start..], style, flow, underline)?;
        }

        Ok(())
    }

    fn append_preserved_text(
        &mut self,
        node_id: NodeId,
        text: &str,
        style: &ComputedStyle,
        flow: &mut InlineFlow,
        underline: bool,
    ) -> Result<(), LayoutError> {
        let expanded = text.replace('\t', "    ");
        let mut segments = expanded.split('\n').peekable();

        while let Some(segment) = segments.next() {
            if !segment.is_empty() {
                self.push_text_fragment(node_id, segment, style, flow, underline, false)?;
            }

            if segments.peek().is_some() {
                let line_height = self.line_height_for(style);

                self.force_line_break(flow, line_height)?;
            }
        }

        Ok(())
    }

    fn append_word(
        &mut self,
        node_id: NodeId,
        word: &str,
        style: &ComputedStyle,
        flow: &mut InlineFlow,
        underline: bool,
    ) -> Result<(), LayoutError> {
        if word.is_empty() {
            return Ok(());
        }

        self.ensure_line(flow)?;

        let text_style = text_style_from_computed(style);

        let word_width = self.shaper.measure(word, text_style).advance();

        let space_width = self.shaper.measure(" ", text_style).advance();

        let has_content = flow.line.is_some_and(|line| line.used_width > 0.0);

        let leading_space = flow.pending_space && has_content;
        let needed_width = word_width + if leading_space { space_width } else { 0.0 };

        let used_width = flow.line.map(|line| line.used_width).unwrap_or_default();

        if has_content && used_width + needed_width > flow.width {
            self.finish_line(flow, 0.0)?;
            self.ensure_line(flow)?;

            self.push_text_fragment(node_id, word, style, flow, underline, false)?;
        } else {
            self.push_text_fragment(node_id, word, style, flow, underline, leading_space)?;
        }

        flow.pending_space = false;

        Ok(())
    }

    fn push_text_fragment(
        &mut self,
        node_id: NodeId,
        text: &str,
        style: &ComputedStyle,
        flow: &mut InlineFlow,
        underline: bool,
        leading_space: bool,
    ) -> Result<(), LayoutError> {
        self.ensure_line(flow)?;

        let Some(line) = flow.line else {
            return Ok(());
        };

        let extra = usize::from(leading_space);
        let len_usize = text
            .len()
            .checked_add(extra)
            .ok_or(LayoutError::TextCapacityExceeded)?;

        let start =
            u32::try_from(self.text.len()).map_err(|_| LayoutError::TextCapacityExceeded)?;

        let len = u32::try_from(len_usize).map_err(|_| LayoutError::TextCapacityExceeded)?;

        if leading_space {
            self.text.push(' ');
        }

        self.text.push_str(text);

        let text_style = text_style_from_computed(style);

        let fragment_width = self.shaper.measure(text, text_style).advance()
            + if leading_space {
                self.shaper.measure(" ", text_style).advance()
            } else {
                0.0
            };

        let fragment_height = self.shaper.font_metrics(text_style).line_height();

        self.push_box(BoxSpec {
            source_node: node_id,
            parent: Some(line.id),
            kind: LayoutKind::Text {
                start,
                len,
                underline,
            },
            rect: Rect::new(
                line.cursor_x,
                flow.cursor_y,
                fragment_width,
                fragment_height,
            ),
            margin: EdgeSizes::zero(),
            padding: EdgeSizes::zero(),
            border: EdgeSizes::zero(),
        })?;

        if let Some(open_line) = flow.line.as_mut() {
            open_line.cursor_x += fragment_width;
            open_line.used_width += fragment_width;
            open_line.height = open_line.height.max(fragment_height);
        }

        Ok(())
    }

    fn ensure_line(&mut self, flow: &mut InlineFlow) -> Result<(), LayoutError> {
        if flow.line.is_some() {
            return Ok(());
        }

        let id = self.push_box(BoxSpec {
            source_node: flow.source_node,
            parent: Some(flow.parent),
            kind: LayoutKind::Line,
            rect: Rect::new(flow.x, flow.cursor_y, 0.0, 0.0),
            margin: EdgeSizes::zero(),
            padding: EdgeSizes::zero(),
            border: EdgeSizes::zero(),
        })?;

        flow.line = Some(OpenLine {
            id,
            cursor_x: flow.x,
            used_width: 0.0,
            height: 0.0,
        });

        Ok(())
    }

    fn force_line_break(
        &mut self,
        flow: &mut InlineFlow,
        fallback_height: f32,
    ) -> Result<(), LayoutError> {
        self.ensure_line(flow)?;
        self.finish_line(flow, fallback_height)
    }

    fn finish_line(
        &mut self,
        flow: &mut InlineFlow,
        fallback_height: f32,
    ) -> Result<(), LayoutError> {
        let Some(line) = flow.line.take() else {
            return Ok(());
        };

        let height = line.height.max(fallback_height).max(1.0);

        self.set_box_rect(
            line.id,
            Rect::new(flow.x, flow.cursor_y, line.used_width, height),
        )?;

        flow.cursor_y += height;
        flow.pending_space = false;

        Ok(())
    }

    fn line_height_for(&self, style: &ComputedStyle) -> f32 {
        self.shaper
            .font_metrics(text_style_from_computed(style))
            .line_height()
    }

    fn push_box(&mut self, spec: BoxSpec) -> Result<LayoutId, LayoutError> {
        let compact_index =
            u32::try_from(self.boxes.len()).map_err(|_| LayoutError::BoxCapacityExceeded)?;

        let id = LayoutId(compact_index);

        self.boxes.push(LayoutBox {
            id,
            source_node: spec.source_node,
            parent: spec.parent,
            first_child: None,
            next_sibling: None,
            kind: spec.kind,
            rect: spec.rect,
            margin: spec.margin,
            padding: spec.padding,
            border: spec.border,
        });

        self.last_child.push(None);

        if let Some(parent_id) = spec.parent {
            self.attach_child(parent_id, id)?;
        }

        Ok(id)
    }

    fn attach_child(&mut self, parent: LayoutId, child: LayoutId) -> Result<(), LayoutError> {
        let parent_index =
            usize::try_from(parent.0).map_err(|_| LayoutError::BoxCapacityExceeded)?;

        let previous_child = self.last_child.get(parent_index).copied().flatten();

        if let Some(previous_id) = previous_child {
            let previous_index =
                usize::try_from(previous_id.0).map_err(|_| LayoutError::BoxCapacityExceeded)?;

            let previous_box = self
                .boxes
                .get_mut(previous_index)
                .ok_or(LayoutError::BoxCapacityExceeded)?;

            previous_box.next_sibling = Some(child);
        } else {
            let parent_box = self
                .boxes
                .get_mut(parent_index)
                .ok_or(LayoutError::BoxCapacityExceeded)?;

            parent_box.first_child = Some(child);
        }

        let parent_last_child = self
            .last_child
            .get_mut(parent_index)
            .ok_or(LayoutError::BoxCapacityExceeded)?;

        *parent_last_child = Some(child);

        Ok(())
    }

    fn set_box_rect(&mut self, id: LayoutId, rect: Rect) -> Result<(), LayoutError> {
        let index = usize::try_from(id.0).map_err(|_| LayoutError::BoxCapacityExceeded)?;

        let layout_box = self
            .boxes
            .get_mut(index)
            .ok_or(LayoutError::BoxCapacityExceeded)?;

        layout_box.rect = rect;

        Ok(())
    }
}

fn resolve_axis_length(length: Length, auto_value: f32, containing_size: f32) -> f32 {
    match length {
        Length::Auto => auto_value,
        Length::Px(value) => value.max(0.0),
        Length::Percent(percent) => (containing_size * (percent / 100.0)).max(0.0),
    }
}

fn resolve_min_constraint(length: Length, containing_size: f32) -> f32 {
    match length {
        Length::Auto => 0.0,
        Length::Px(value) => value.max(0.0),
        Length::Percent(percent) => (containing_size * (percent / 100.0)).max(0.0),
    }
}

fn resolve_max_constraint(length: Length, containing_size: f32) -> Option<f32> {
    match length {
        Length::Auto => None,
        Length::Px(value) => Some(value.max(0.0)),
        Length::Percent(percent) => Some((containing_size * (percent / 100.0)).max(0.0)),
    }
}

fn resolve_height_length(length: Length, auto_value: f32) -> f32 {
    match length {
        Length::Auto | Length::Percent(_) => auto_value,
        Length::Px(value) => value.max(0.0),
    }
}

fn resolve_min_height_constraint(length: Length) -> f32 {
    match length {
        Length::Auto | Length::Percent(_) => 0.0,
        Length::Px(value) => value.max(0.0),
    }
}

fn resolve_max_height_constraint(length: Length) -> Option<f32> {
    match length {
        Length::Auto | Length::Percent(_) => None,
        Length::Px(value) => Some(value.max(0.0)),
    }
}

fn clamp_axis(value: f32, minimum: f32, maximum: Option<f32>) -> f32 {
    let effective_maximum = maximum.map_or(f32::INFINITY, |maximum| maximum.max(minimum));

    value.clamp(minimum, effective_maximum)
}

fn sanitize_viewport_width(viewport_width: f32) -> f32 {
    if viewport_width.is_finite() {
        viewport_width.max(1.0)
    } else {
        1024.0
    }
}

fn is_pre_element(document: &Document, node_id: NodeId) -> bool {
    document
        .node(node_id)
        .and_then(|node| match node.kind() {
            NodeKind::Element(element) => Some(element.tag_name() == "pre"),
            _ => None,
        })
        .unwrap_or(false)
}

fn text_style_from_computed(style: &ComputedStyle) -> TextStyle {
    let family = match style.font_family() {
        CssFontFamily::SansSerif => TextFontFamily::SansSerif,

        CssFontFamily::Monospace => TextFontFamily::Monospace,
    };

    let weight = match style.font_weight() {
        CssFontWeight::Normal => TextFontWeight::Normal,

        CssFontWeight::Bold => TextFontWeight::Bold,
    };

    let slant = match style.font_style() {
        CssFontStyle::Normal => TextFontSlant::Normal,

        CssFontStyle::Italic => TextFontSlant::Italic,
    };

    TextStyle::new(style.font_size(), family, weight, slant)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use phantom_css::compute_styles;
    use phantom_dom::{Document, DomError, ElementData, NodeKind};

    use super::{LayoutKind, build_layout_snapshot};

    #[test]
    fn inline_text_shares_one_line_when_space_exists() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let paragraph = document.append_child(root, NodeKind::Element(ElementData::new("p")))?;

        document.append_child(paragraph, NodeKind::Text("Hello ".to_owned()))?;

        let strong =
            document.append_child(paragraph, NodeKind::Element(ElementData::new("strong")))?;

        document.append_child(strong, NodeKind::Text("Phantom".to_owned()))?;

        document.append_child(paragraph, NodeKind::Text(" world".to_owned()))?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 800.0)?;

        assert_eq!(snapshot.line_count(), 1);
        assert_eq!(snapshot.text_fragment_count(), 3);

        Ok(())
    }

    #[test]
    fn whitespace_wraps_into_multiple_line_boxes() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let paragraph = document.append_child(root, NodeKind::Element(ElementData::new("p")))?;

        document.append_child(
            paragraph,
            NodeKind::Text("one two three four five six seven".to_owned()),
        )?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 90.0)?;

        assert!(snapshot.line_count() >= 3);
        assert!(snapshot.content_height() > 0.0);

        Ok(())
    }

    #[test]
    fn br_forces_a_new_line() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let paragraph = document.append_child(root, NodeKind::Element(ElementData::new("p")))?;

        document.append_child(paragraph, NodeKind::Text("before".to_owned()))?;

        document.append_child(paragraph, NodeKind::Element(ElementData::new("br")))?;

        document.append_child(paragraph, NodeKind::Text("after".to_owned()))?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 600.0)?;

        assert_eq!(snapshot.line_count(), 2);

        Ok(())
    }

    #[test]
    fn pre_preserves_hard_newlines() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let pre = document.append_child(root, NodeKind::Element(ElementData::new("pre")))?;

        document.append_child(pre, NodeKind::Text("first\nsecond\nthird".to_owned()))?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 600.0)?;

        assert_eq!(snapshot.line_count(), 3);

        Ok(())
    }

    #[test]
    fn display_none_removes_subtree() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let mut attributes = BTreeMap::new();
        attributes.insert("style".to_owned(), "display: none".to_owned());

        let hidden = document.append_child(
            root,
            NodeKind::Element(ElementData::with_attributes("div", attributes)),
        )?;

        document.append_child(hidden, NodeKind::Text("Invisible".to_owned()))?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 800.0)?;

        assert_eq!(snapshot.len(), 1);
        assert_eq!(snapshot.text_bytes(), 0);

        Ok(())
    }

    #[test]
    fn percent_width_and_padding_generate_geometry() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let mut attributes = BTreeMap::new();
        attributes.insert("style".to_owned(), "width: 50%; padding: 10px".to_owned());

        let element = document.append_child(
            root,
            NodeKind::Element(ElementData::with_attributes("div", attributes)),
        )?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 1000.0)?;

        let width = snapshot
            .boxes()
            .iter()
            .find(|layout_box| {
                layout_box.source_node() == element && layout_box.kind() == LayoutKind::Block
            })
            .map(|layout_box| layout_box.rect().width())
            .unwrap_or_default();

        assert!((width - 520.0).abs() < f32::EPSILON);

        Ok(())
    }

    #[test]
    fn append_relationships_remain_stable() -> Result<(), DomError> {
        let mut document = Document::new();
        let root = document.root();

        let paragraph = document.append_child(root, NodeKind::Element(ElementData::new("p")))?;

        assert_eq!(
            document.node(paragraph).and_then(|node| node.parent()),
            Some(root)
        );

        Ok(())
    }

    #[test]
    fn content_box_adds_padding_and_border_to_outer_width() -> Result<(), Box<dyn std::error::Error>>
    {
        let mut document = Document::new();
        let root = document.root();

        let mut attributes = BTreeMap::new();
        attributes.insert(
            "style".to_owned(),
            "width: 100px; padding: 10px; border: 5px solid #000".to_owned(),
        );

        let element = document.append_child(
            root,
            NodeKind::Element(ElementData::with_attributes("div", attributes)),
        )?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 800.0)?;

        let width = snapshot
            .boxes()
            .iter()
            .find(|layout_box| {
                layout_box.source_node() == element && layout_box.kind() == LayoutKind::Block
            })
            .map(|layout_box| layout_box.rect().width())
            .unwrap_or_default();

        assert!((width - 130.0).abs() < f32::EPSILON);

        Ok(())
    }

    #[test]
    fn border_box_keeps_declared_outer_width() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let mut attributes = BTreeMap::new();
        attributes.insert(
            "style".to_owned(),
            "box-sizing: border-box; width: 100px; \
             padding: 10px; border: 5px solid #000"
                .to_owned(),
        );

        let element = document.append_child(
            root,
            NodeKind::Element(ElementData::with_attributes("div", attributes)),
        )?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 800.0)?;

        let layout_box = snapshot.boxes().iter().find(|layout_box| {
            layout_box.source_node() == element && layout_box.kind() == LayoutKind::Block
        });

        assert_eq!(
            layout_box.map(|layout_box| layout_box.border().left()),
            Some(5.0)
        );

        let width = layout_box
            .map(|layout_box| layout_box.rect().width())
            .unwrap_or_default();

        assert!((width - 100.0).abs() < f32::EPSILON);

        Ok(())
    }

    #[test]
    fn max_width_clamps_declared_width() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let mut attributes = BTreeMap::new();
        attributes.insert(
            "style".to_owned(),
            "width: 500px; max-width: 200px".to_owned(),
        );

        let element = document.append_child(
            root,
            NodeKind::Element(ElementData::with_attributes("div", attributes)),
        )?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 800.0)?;

        let width = snapshot
            .boxes()
            .iter()
            .find(|layout_box| {
                layout_box.source_node() == element && layout_box.kind() == LayoutKind::Block
            })
            .map(|layout_box| layout_box.rect().width())
            .unwrap_or_default();

        assert!((width - 200.0).abs() < f32::EPSILON);

        Ok(())
    }

    #[test]
    fn min_height_clamps_border_box_height() -> Result<(), Box<dyn std::error::Error>> {
        let mut document = Document::new();
        let root = document.root();

        let mut attributes = BTreeMap::new();
        attributes.insert(
            "style".to_owned(),
            "box-sizing: border-box; height: 10px; \
             min-height: 40px; padding: 4px; border: 2px solid #000"
                .to_owned(),
        );

        let element = document.append_child(
            root,
            NodeKind::Element(ElementData::with_attributes("div", attributes)),
        )?;

        let styles = compute_styles(&document);
        let snapshot = build_layout_snapshot(&document, &styles, 800.0)?;

        let height = snapshot
            .boxes()
            .iter()
            .find(|layout_box| {
                layout_box.source_node() == element && layout_box.kind() == LayoutKind::Block
            })
            .map(|layout_box| layout_box.rect().height())
            .unwrap_or_default();

        assert!((height - 40.0).abs() < f32::EPSILON);

        Ok(())
    }
}
